name: Feature Request
description: Suggest an idea for Paladin.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        We are always looking for ways to make Paladin more immersive!
  - type: textarea
    id: feature-description
    attributes:
      label: Description of the feature
      description: A clear and concise description of what the feature is.
    validations:
      required: true
  - type: textarea
    id: problem-solved
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: alternative-solutions
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
